@echo off
echo Building and creating containers...
docker-compose up -d
echo Waiting for SQL Server to be ready...
powershell.exe -Command "Start-Sleep -Seconds 90"
echo Creating database...
sqlcmd -S localhost -U sa -P "teleMedicina@test" -d "master" -i setup.sql
echo Finished.